# server config
server:
  port: 10010

# spring config
spring:
  application:
    name: eureka-server # eureka服务名称

# eureka config
eureka:
  client:
    service-url:   # eureka服务地址信息
      defaultZone: http://localhost:10010/eureka
